// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupRolloutPrefs.media.peerconnection.mtransport_process", true);
user_pref("app.normandy.startupRolloutPrefs.network.process.enabled", true);
user_pref("app.normandy.user_id", "606fffd7-4193-48ac-8b59-cb520a8b35f6");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1649123179);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1649123178);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{77879fb8-7a1b-43ea-9919-e390fc0f98f6}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1649123176);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 122);
user_pref("browser.newtabpage.activity-stream.impressionId", "{805cac39-a3d5-48b9-b451-2824d476c2a9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1649123178);
user_pref("browser.search.region", "ID");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220323001514");
user_pref("browser.startup.homepage_override.mstone", "98.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1649123177);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1649123177687");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "98.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "ID");
user_pref("dom.push.userAgentID", "88b46529c45d46d0bd615ac35dfacc5f");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220323001514");
user_pref("extensions.lastAppVersion", "98.0.2");
user_pref("extensions.lastPlatformVersion", "98.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"699df9c8-6c12-4df0-b00d-63c10d091e6e\",\"formautofill@mozilla.org\":\"ce66911f-9c6a-4ad8-b362-172d707614d5\",\"pictureinpicture@mozilla.org\":\"23fd1d75-2dd1-4d63-b4eb-97c86f75e29f\",\"screenshots@mozilla.org\":\"996ba825-5014-429e-b4ff-21ff9c486420\",\"webcompat-reporter@mozilla.org\":\"484bf0db-9c88-40f8-9af6-15761cd96e76\",\"webcompat@mozilla.org\":\"deb7d4fe-3a3e-4b1c-81a6-17441c7789bd\",\"default-theme@mozilla.org\":\"964235e2-42d8-4c1f-aef7-9ab29a23a09b\",\"addons-search-detection@mozilla.com\":\"2d454c4e-fd3f-4704-9774-c118a147dec4\",\"google@search.mozilla.org\":\"7a5a1202-b40d-44ac-bc8d-347f8e373b36\",\"amazondotcom@search.mozilla.org\":\"e284053f-556f-494a-b057-92e0a9438387\",\"wikipedia@search.mozilla.org\":\"431a97d0-49b2-44cb-a09b-296996e33783\",\"bing@search.mozilla.org\":\"0e178526-180e-4872-97a0-07a4b0be8337\",\"ddg@search.mozilla.org\":\"439d9068-adf7-4f06-90fc-42be96ee6c35\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1649123177);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "81f57bd4-b88e-440d-86dc-54eaabf0186c");
user_pref("toolkit.startup.last_success", 1649123175);
user_pref("toolkit.telemetry.cachedClientID", "e7f096bb-1875-4882-b7b0-af56df0ff583");
user_pref("toolkit.telemetry.previousBuildID", "20220323001514");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
